language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "nightly"
install:
    - pip install -r test-requirements.txt
    - pip install -e ./
script:
    - if [[ ! "$(python --version 2>&1)" =~ Python\ (3\.7.*) ]]; then pep8 aitertools/; fi
    - if [[ ! "$(python --version 2>&1)" =~ Python\ (3\.7.*) ]]; then pep8 tests/; fi
    - pep257 --add-select=D203 --add-ignore=D211 aitertools/
    - pep257 --add-select=D203 --add-ignore=D211 tests/
    - pyflakes aitertools/
    - pyflakes tests/
    - py.test tests/
